---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by HP.
--- DateTime: 2025/1/12 23:27
---
local key = KEYS[1]
local result = redis.call("DEL", key)
if result == 1 then
    return "success"
else
    return "fail"
end